services:
  - type: web
    name: english-tracker-api
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001
    rootDir: server
